export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const ADD_PRODUCTS_START = 'ADD_PRODUCTS_START';
export const ADD_PRODUCTS_ERROR = 'ADD_PRODUCTS_ERROR';
export const ADD_PRODUCTS_SUCCESS = 'ADD_PRODUCTS_SUCCESS';